use std::ffi::CString;
use std::path::Path;

pub fn patch_kernel_bin(input: &Path, output: &Path, root_key: Option<&str>) -> Result<String, String> {
    let c_input = CString::new(input.to_string_lossy().as_bytes()).map_err(|e| e.to_string())?;
    let c_output = CString::new(output.to_string_lossy().as_bytes()).map_err(|e| e.to_string())?;
    let c_key = root_key.and_then(|k| CString::new(k).ok());

    let ret = unsafe {
        patch_kernel(
            c_input.as_ptr(),
            c_output.as_ptr(),
            c_key.as_ref().map_or(std::ptr::null(), |k| k.as_ptr()),
        )
    };

    if ret == 0 {
        Ok(root_key.unwrap_or("<auto-generated>").to_string())
    } else {
        Err(format!("error code {}", ret))
    }
}

unsafe extern "C" {
    fn patch_kernel(
        input_path: *const std::ffi::c_char,
        output_path: *const std::ffi::c_char,
        root_key: *const std::ffi::c_char,
    ) -> i32;
}
